#!/bin/bash
number=0
tag=fresh
blocks=75
blocksize=1M
dumpsize=75M



echo -e "\nListing Disks"
lsblk
echo -e "\nEnter disk (e.x. sda or sdb - BE CAREFUL)"
read disk
block=/dev/$disk

timestamp=$(date "+%d%m%Y-%H.%M.%S-%Z")

filename="./imgs/${number}-${tag}-${dumpsize}-${timestamp}.img"

echo -e "\nWriting to ${filename}"
sudo dd if=$block of=$filename bs=$blocksize count=$blocks status=progress conv=fdatasync

echo -e "\n\nDONE\n\nWritten to: ${filename}\n\n"
